### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by madscientist159** [openbmc/openpower-proc-control#2]
On latest master (e3599a8a1168998b69f00fde9c8b4a9982818959)

```
| openpower_procedures.cpp: In function 'void openpower::openfsi::scan()':
| openpower_procedures.cpp:542:26: error: 'org' does not name a type; did you mean 'long'?
|          using metadata = org::open_power::Proc::FSI::MasterDetectionFailure;
|                           ^~~
|                           long
| openpower_procedures.cpp:545:17: error: 'metadata' has not been declared
|                  metadata::CALLOUT_ERRNO(e.code().value()),
|                  ^~~~~~~~
| openpower_procedures.cpp:546:17: error: 'metadata' has not been declared
|                  metadata::CALLOUT_DEVICE_PATH(masterCalloutPath));
|                  ^~~~~~~~
| openpower_procedures.cpp:553:26: error: 'org' does not name a type; did you mean 'long'?
|          using metadata = org::open_power::Proc::FSI::MasterDetectionFailure;
|                           ^~~
|                           long
| openpower_procedures.cpp:556:17: error: 'metadata' has not been declared
|                  metadata::CALLOUT_ERRNO(0),
|                  ^~~~~~~~
| openpower_procedures.cpp:557:17: error: 'metadata' has not been declared
|                  metadata::CALLOUT_DEVICE_PATH(masterCalloutPath));
|                  ^~~~~~~~
| openpower_procedures.cpp:574:26: error: 'org' does not name a type; did you mean 'long'?
|          using metadata = org::open_power::Proc::FSI::SlaveDetectionFailure;
|                           ^~~
|                           long
| openpower_procedures.cpp:577:17: error: 'metadata' has not been declared
|                  metadata::ERRNO(e.code().value()));
|                  ^~~~~~~~
| Makefile:614: recipe for target 'openpower_proc_control-openpower_procedures.o' failed
```

**Comment by amboar** [comment]
Can you revert your patch and instead try `rm -rf build/conf` and then rebuilding? @bradbishop should be able to clarify, but I believe openbmc/openbmc@509842add85b53e13164c1569a1fd43d5b8d91c5 made the clean-out of existing conf dirs necessary.

**Comment by madscientist159** [comment]
@amboar This was with a clean build, downloaded straight from GIT and built inside Yocto.

**Comment by amboar** [comment]
Okay, can you elaborate on what you mean by "downloaded straight from GIT" and "built inside Yocto"? Are you talking about building it via openbmc/openbmc? Or the SDK? I had assumed you'd pulled in the latest openbmc/openbmc@master and hit the build error, but now I'm feeling the ambiguity. Can you copy/paste all of the commandlines you used to hit the error? In either case, what you have may be out of date, and in the case of an openbmc/openbmc build, the cache may not have been properly invalidated.

To clarify, openpower-proc-control depends on headers generated from openpower-dbus-interfaces. The issues with bad types can be caused by the generated code not being present in the elog-errors.h file that is included in the build process.

**Comment by madscientist159** [comment]
@amboar I'm an idiot :frowning:  The reason it wasn't building inside Yocto was that our tree was still set to the phosphor distro instead of the openpower distro.  Looks like it's building fine now.
